env:
    TERM: alacritty
window:
    padding:
        x: 2
        y: 2
    decorations: none
    dynamic_title: true
font:
    normal:
        family: "Terminus (TTF)"
        style: regular
    bold:
        family: "Terminus (TTF)"
        style: regular
    italic:
        family: "Terminus (TTF)"
        style: Italic
    bold_italic:
        family: "Terminus (TTF)"
        style: Italic
    size: 10.0
bell:
    duration: 0
background_opacity: 1.0
cursor:
    style: Block
live_config_reload: true
shell:
    program: /bin/bash
    args:
        - --login
url:
    launcher:
        program: xdg-open
        args: []
key_bindings:
    - { key: V, mods: Control|Shift, action: Paste }
    - { key: C, mods: Control|Shift, action: Copy }
# Campbell (Windows 10 default)
colors:
  # Default colors
  primary:
    background: '#0c0c0c'
    foreground: '#cccccc'

  # Normal colors
  normal:
    black:      '#0c0c0c'
    red:        '#c50f1f'
    green:      '#13a10e'
    yellow:     '#c19c00'
    blue:       '#0037da'
    magenta:    '#881798'
    cyan:       '#3a96dd'
    white:      '#cccccc'

  # Bright colors
  bright:
    black:      '#767676'
    red:        '#e74856'
    green:      '#16c60c'
    yellow:     '#f9f1a5'
    blue:       '#3b78ff'
    magenta:    '#b4009e'
    cyan:       '#61d6d6'
    white:      '#f2f2f2'
