[colors.bright]
black = "#767676"
blue = "#3B78FF"
cyan = "#61D6D6"
green = "#16C60C"
magenta = "#B4009E"
red = "#E74856"
white = "#F2F2F2"
yellow = "#F9F1A5"

[colors.cursor]
cursor = "#F9F1A5"
text = "#1d1f21"

[colors.normal]
black = "#000000"
blue = "#0037DA"
cyan = "#3A96DD"
green = "#13A10E"
magenta = "#881798"
red = "#C50F1F"
white = "#CCCCCC"
yellow = "#C19C00"

[colors.primary]
background = "#000000"
foreground = "#CCCCCC"

[colors.selection]
background = "#323539"
foreground = "#ffffff"

[cursor]
thickness = 0.4
unfocused_hollow = false

[cursor.style]
blinking = "on"
shape = "underline"

[font]
size = 9.0

[font.bold]
family = "Berkeley Mono"
style = "Bold"

[font.bold_italic]
family = "Berkeley Mono"
style = "Bold Italic"

[font.italic]
family = "Berkeley Mono"
style = "Italic"

[font.normal]
family = "Berkeley Mono"
style = "Regular"

[window]
decorations_theme_variant = "Dark"
dynamic_title = true
title = "terminal"
opacity = 0.8
blur = true

[window.padding]
x = 8
y = 8
