#!/bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config active_border_color "#007aff"
bspc config focused_border_color "#007aff"
bspc config window_gap 10
bspc config split_ratio 0.52

xrandr --output DP-2 --set "TearFree" on --primary
xset r rate 200 60

compton &
yabar &
