#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV

bspc config border_width 2
bspc config window_gap 12
bspc config bottom_padding 8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color "#d4d0c8"
bspc config normal_border_color "#1e1e1e"

bspc rule -a Xfce4-appfinder state=floating
