theme = "self"

[editor]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "error"

[editor.file-picker]
hidden = false

[keys.normal]
x = "delete_selection"
esc = ["collapse_selection"]
